### ISSUE TITLE
How to simulate homozygous deletion

### ISSUE THREAD

**Issue by pcgen1** [pughlab/bamgineer#11]
Hi suluxan, May I know the best way to simulate a homozygous deletion?
Should the entry be mentioned (as stated below) in the cnv intereset bed:

chr1    123     124   <empty string>    0

**Comment by pcgen1** [comment]
I meant:
chr1     123     124   "empty string"    0

**Comment by pcgen1** [comment]
sorry for mentioning very close stop , consider start to be 123 and stop to be 323 for example... :-)..
Please let me know

**Comment by suluxan** [comment]
A lot of the updates to bamgineer v2 focused on user-specified allels so the code was tailored towards specifying the haplotype. Homozygous deletions were already in the code but the input might fail in v2 since there is no associated haplotype code (i.e. AB). I will implement it as soon as possible and get back to you. 

Thanks for your input!

**Comment by pcgen1** [comment]
I just checked the results: my input trial (as mentioned) below to simulate homozygous deletions WORKED!
chr1 123 124  AB  0

**Comment by suluxan** [comment]
Awesome! Yeah there are no restrictions to what your haplotype code would be as there should be no reads anyway! So AAAAA would work or any combination. Will fix this to make it more obvious and ability to put "NA" or something along those lines. Thanks!

**Comment by suluxan** [comment]
Awesome! Yeah there are no restrictions to what your haplotype code would be as there should be no reads anyway! So AAAAA would work or any combination. Will fix this to make it more obvious and ability to put "NA" or something along those lines. Thanks!
